modeYum:
  - action: "install"
    name:
      - perl-XML-LibXML
      - perl-XML-DOM
      - perl-Switch
      - ipmitool
      - lrzsz
      - traceroute
      - sysstat
      - psmisc
      - bash-completion
      - tcpdump
      - mtr
      - nmap-ncat
      - tree
      - screen
      - ntp
modeService:
  - status: inactive
    name:
      - NetworkManager.service
  - status: active
    name:
      - ntpd.service
modeDir:
  - action: chown
    host: mhxzx_manager
    para: "mhxzx.mhxzx"
    path:
      - /export/logs
  - action: chmod
    host: mhxzx_manager
    perm: 0600
    path:
      - /dbhome/doumaoxin

modeScripts:
  - action: run
    host: all
    env: python
    name:
      # 防火墙初始化
      - ./tools/mhxzx_iptables_init.py
  - action: run
    host: mhxzx_manager
    env : sh
    name:
      - ./tools/addcron.sh
      - ./tools/checkIweb.sh
