modeYum:
  - action: "install"
    name:
    - ethtool
    - tcpdump

modeDir:
  - action: "chown"
    para: "mhxzx.mhxzx"
    path:
    - /export/web
  - ation: "chmod"
    perm: 0600
    path:
    - /export/web

modeScripts:
  - action: "run"
    env: "python"
    name:
    - ./tools/sayhello.py
  - action: "run"
    env : "shell"
    name:
    - ./tools/kill.sh
  - action: "run"
    env: "golang"
    name:
      - ./tools/doubles